# Week 2, Days 4 & 5, Part 1
### Numpy and list, more numpy

In [4]:
import numpy as np
import sys
a_l=[1,2,3]
a_l

[1, 2, 3]

In [5]:
a_l=['a',1]
a_l

['a', 1]

In [20]:
a=np.array([1,2,3])
a


array([1, 2, 3])

In [7]:
a=np.array([1,'a'])
a

array(['1', 'a'], dtype='<U21')

In [9]:
a.dtype

dtype('int64')

In [10]:
print(a*3) # Item wise multiplication

[3 6 9]


In [11]:
print(a_l*3) # List multiplication

['a', 1, 'a', 1, 'a', 1]


In [21]:
size_list=sys.getsizeof(1)*len(a_l)
size_nu=a.itemsize*a.size
print (f"the size of same values of list is {size_list} and array is {size_nu}")

the size of same values of list is 56 and array is 24


In [18]:
size_nu=a.itemsize*a.size
size_nu

24

In [22]:
a=[[1,2],[3,4],[3,6]]
a

[[1, 2], [3, 4], [3, 6]]

In [24]:
np.shape(a)

(3, 2)

In [27]:
# Create a array 
a=np.arange(0,10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
a=np.arange(0,10,.5)
a

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [30]:
np.shape(a)

(20,)

In [32]:
a=np.arange(0,10,2)
a

array([0, 2, 4, 6, 8])

In [33]:
np.shape(a)

(5,)

In [40]:
a=np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [41]:
a=np.ones(10)
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [43]:
a=np.ones((5,2))
a

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [45]:
a=np.zeros((5,2))
a

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

# Let's perform math functions

In [53]:
a=np.array([1,2,3,4,5,6])

In [48]:
np.max(a)

6

In [49]:
np.min(a)

1

In [50]:
np.sum(a)

21

In [51]:
a=np.ones((5,2))
np.sum(a)

10.0

In [55]:
a=np.array([1,2,3,4,5,6])
np.mean(a)

3.5

In [56]:
a=a+1
a

array([2, 3, 4, 5, 6, 7])

In [62]:
a=np.array([1,3,5,7])
b=np.array([2,4,6,9])
c=a+b
c

array([ 3,  7, 11, 16])

In [63]:
c=a*b
c

array([ 2, 12, 30, 63])

In [64]:
np.sqrt(c)

array([1.41421356, 3.46410162, 5.47722558, 7.93725393])

In [65]:
a=np.array([1,2,3,4,5])

In [66]:
a[1]

2

In [67]:
a[0]

1

In [69]:
a[:]

array([1, 2, 3, 4, 5])

In [70]:
a[0:2]

array([1, 2])

In [71]:
a[1:]

array([2, 3, 4, 5])

In [72]:
a[:-1]

array([1, 2, 3, 4])

In [98]:
a=np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])
a


array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [87]:
a[0:1,0:1]

array([[1]])

In [88]:
a[0:1,]

array([[1, 2]])

In [89]:
a[0:1,0:]

array([[1, 2]])

In [90]:
a[0:4,]

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [91]:
a[3:4,]

array([[7, 8]])

In [92]:
a[3:4,:-1]

array([[7]])

In [97]:
a=100
a

100

In [102]:
a=np.array([[1,2,1],[3,4,1],[5,6,1],[7,8,1],[9,10,0]])
a

array([[ 1,  2,  1],
       [ 3,  4,  1],
       [ 5,  6,  1],
       [ 7,  8,  1],
       [ 9, 10,  0]])

In [103]:
a[2:3,]

array([[5, 6, 1]])

In [104]:
a[2:3,-1]

array([1])

In [105]:
a[2:3,1:2]

array([[6]])

# Filter rows

In [112]:
a

array([[ 1,  2,  1],
       [ 3,  4,  1],
       [ 5,  6,  1],
       [ 7,  8,  1],
       [ 9, 10,  0]])

In [113]:
np.where(a<3)

(array([0, 0, 0, 1, 2, 3, 4]), array([0, 1, 2, 2, 2, 2, 2]))

In [117]:
a=np.array([1,2,3,4,5,10])
np.where(a<3)

(array([0, 1]),)

In [121]:
np.where(a>3)

(array([3, 4, 5]),)

In [120]:
a[np.where(a>3)]

array([ 4,  5, 10])

In [122]:
a

array([ 1,  2,  3,  4,  5, 10])

In [126]:
a[0:1]=100
a

array([100,   2,   3,   4,   5,  10])

In [130]:
a[2:5]=120
a

array([100,   2, 120, 120, 120,  10])

In [141]:
a=np.array([[1.,2.,1.],[3.,4.,1.],[5.,6.,1.],[7.,8.,1.],[9.,10.,0.]])
a

array([[ 1.,  2.,  1.],
       [ 3.,  4.,  1.],
       [ 5.,  6.,  1.],
       [ 7.,  8.,  1.],
       [ 9., 10.,  0.]])

In [143]:
a[:,-1]=0
a

array([[ 1.,  2.,  0.],
       [ 3.,  4.,  0.],
       [ 5.,  6.,  0.],
       [ 7.,  8.,  0.],
       [ 9., 10.,  0.]])

In [149]:
a[2,2]=np.nan
a


array([[ 1.,  2.,  0.],
       [ 3.,  4.,  0.],
       [ 5.,  6., nan],
       [ 7.,  8., inf],
       [ 9., 10.,  0.]])

In [145]:
a[3,2]=np.inf
a

array([[ 1.,  2.,  0.],
       [ 3.,  4.,  0.],
       [ 5.,  6., nan],
       [ 7.,  8., inf],
       [ 9., 10.,  0.]])

In [148]:
a[np.isnan(a)]=999
a

array([[  1.,   2.,   0.],
       [  3.,   4.,   0.],
       [  5.,   6., 999.],
       [  7.,   8.,  inf],
       [  9.,  10.,   0.]])

In [150]:
a[np.isnan(a)]=np.mean(a)
a

array([[ 1.,  2.,  0.],
       [ 3.,  4.,  0.],
       [ 5.,  6., nan],
       [ 7.,  8., inf],
       [ 9., 10.,  0.]])

In [151]:
np.mean(a)

nan

In [154]:
a[np.isnan(a)]=0
a[np.isinf(a)]=0

In [155]:
np.mean(a)

3.6666666666666665

In [157]:
a=[1,2,3,4,5,6,7,8,0]
b=[1,2,3,4,5,6,7,8,9]
np.setdiff1d(b,a)

array([9])

In [158]:
a=[1,2,3,4,5]

In [159]:
a.append(7)
a

[1, 2, 3, 4, 5, 7]

In [162]:
a=np.array([[1.,2.,1.],[3.,4.,1.],[5.,6.,1.],[7.,8.,1.],[9.,10.,0.]])
a

array([[ 1.,  2.,  1.],
       [ 3.,  4.,  1.],
       [ 5.,  6.,  1.],
       [ 7.,  8.,  1.],
       [ 9., 10.,  0.]])